apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pypi-package-project
  title: PyPI Package Project
  description: A PyPI package for handling various tasks and functionalities.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: hinkingmachines/ratchada-utils
  tags:
    - open-source

spec:
  owner: user:your-github-username # Replace with your GitHub username
  type: internal
  lifecycle: development # Switch to production once live
