site_name: 'PyPI Package Documentation'

nav:
  - Introduction: 'README.md'
  - 'Technical Documentation':
    - Architecture: architecture.md
    - Data Flow: dataflow.md
    - Development: development.md
    - Deployment: deployment.md
    - Troubleshooting: troubleshooting.md
  - 'Product / Milestone Documentation':
    - 'Installation Guide': './features/installation_guide.md'
    - 'Usage Examples': './features/usage_examples.md'
    - 'API Reference': './features/api_reference.md'

plugins:
  - techdocs-core
